### ISSUE TITLE
Question: Tailwind & Opacity

### ISSUE THREAD

**Issue by daugaard47** [rough-stuff/rough-notation#46]
1. Is there a way to set the opacity on an Annotation?
Like this `opacity: '75'`
```
const heroTitleColor = annotate(heroTitle, { type: 'highlight', color: 'yellow', opacity: '75' });
```

2. Also is there a way to use custom tailwind colors or padding? 
Like this:
```
const heroTitleColor = annotate(heroTitle, { type: 'highlight', padding: ['py-4', 'px-6'], color: 'custom-yellow-500'});
```

**Comment by pshihn** [comment]
All annotations are created as SVG and they are assigned a class name `rough-annotation` So you may change the opacity via CSS:

```css
svg.rough-annotation {
  opacity: 0.5;
}
```

you could also specify the color using rgba to set the opacity of the color, e.g. `rgba(200, 200, 10, 0.5)` 

As for tailwind, there may be way to set the color using CSS properties perhaps? I am not aware or how tailwind defines colors.

Padding will not be possible because the values are used in computing the geometry, so cannot be set using CSS

**Comment by daugaard47** [comment]
Okay so if I had multiple annotations on my page and I only wanted one to have the opacity of 50%. Is there a way I can call that inline on my element?

**Comment by pshihn** [comment]
well you can add the opacity in the color instead. that's the simplest solution. No CSS. 

```javascript
 annotate(heroTitle, { type: 'highlight', color: 'rgba(255, 255, 255, 0.75)' })
```

In CSS, if you want a spcific annotation you may have to add it to the CSS selector. e.g. Annotation under a div with id 'mydiv' would be

```css
#mydiv svg.rough-annotation {
  opacity: 0.5;
}
```

**Comment by daugaard47** [comment]
Ahh, okay gotcha. Thanks man!
